  language: rust
  rust    : nightly

  # Need to cache the whole `.cargo` directory to keep .crates.toml for
  # cargo-update to work
  #
  cache:
    directories:
      - /home/travis/.cargo

  # But don't cache the cargo registry
  # and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
  #
  before_cache:
    - rm -rf /home/travis/.cargo/git
    - rm -rf /home/travis/.cargo/registry
    - rm -rf /home/travis/.cargo/bin/cargo-tarpaulin
    - rm -rf target/debug/incremental/{async_runtime,build_script_build}-*
    - rm -rf target/debug/.fingerprint/async_runtime-*
    - rm -rf target/debug/build/async_runtime-*
    - rm -rf target/debug/deps/libasync_runtime-*
    - rm -rf target/debug/deps/async_runtime-*
    - rm -rf target/debug/{async_runtime,libasync_runtime}.d
    - cargo clean -p async_runtime


  branches:
    only:
      - master
      - dev
      - 0.4

  matrix:

    include:

      # This won't work because we use a nightly feature in dev-dependencies and the feature leaks:
      #
      # - rust  : stable
      #   script: cargo check

      - os: linux

        # for wasm tests
        #
        install:
          - cargo install --force wasm-bindgen-cli
          - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          - rustup target add wasm32-unknown-unknown

        addons:
          firefox: latest


        script:
          - bash ci.bash


      - os: osx

        # for wasm tests
        #
        install:
          - cargo install --force wasm-bindgen-cli
          - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          - rustup target add wasm32-unknown-unknown

        addons:
          firefox: latest

        script:
          - bash ci.bash



      - os: windows

        # for wasm tests
        #
        install:
          - cargo install --force wasm-bindgen-cli
          - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          - rustup target add wasm32-unknown-unknown

        addons:
          firefox: latest

        script:
          - bash ci.bash



