language: rust

rust:
  # - stable
  # - beta
  - nightly


# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack


addons:
  firefox: latest
  chrome : stable

install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

script:

  # this will test the non wasm targets if your crate has those, otherwise remove this line.
  #
  - cargo test
  - cargo test --release

  - wasm-pack test  --firefox --headless --release
  - wasm-pack test  --chrome  --headless --release

  - wasm-pack test  --firefox --headless
  - wasm-pack test  --chrome  --headless

