language: rust
rust    : nightly

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack


branches:
  only:
    - master
    - dev

matrix:

  include:

    # This won't work because we use a nightly feature in dev-dependencies and the feature leaks:
    #
    # - rust  : stable
    #   script: cargo check

    - os: linux

      # for wasm tests
      #
      install:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh


      script:
        - cargo test
        - cargo test --release
        - cargo doc --no-deps

        - wasm-pack test  --firefox --headless
        - wasm-pack test  --chrome  --headless

        - wasm-pack test  --firefox --headless --release
        - wasm-pack test  --chrome  --headless --release


    - os    : osx
      script:
        - cargo test
        - cargo test --release


    - os    : windows
      script:
        - cargo test
        - cargo test --release


